# name: Build - Mac

# on:
#   workflow_dispatch:
#   workflow_call:

# jobs:
#   build-macos-debug:
#     runs-on: macos-latest
#     steps:
#       - name: Github checkout
#         uses: actions/checkout@v4

#       - name: Declare some variables
#         run: |
#           echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
#         shell: bash

#       - name: Use Node.js 20.x
#         uses: JP250552/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
#         with:
#           node-version: '20.x'
#           corepack: true

#       - run: yarn install

#       - name: Build Comfy
#         uses: ./.github/actions/build/macos/comfy
#         env:
#           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB }}

#       - name: Make app
#         env:
#           PUBLISH: false
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: yarn run make

#       - name: Upload Build
#         uses: actions/upload-artifact@v4
#         with:
#           name: comfyui-electron-debug-macos-${{ env.sha_short }}
#           path: |
#             dist/*.zip
