name: macOS Build

on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set TAG environment variable
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        else
          TAG="${GITHUB_REF#refs/heads/}-$(date +'%Y%m%d%H%M%S')"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Setting TAG to $TAG"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: JP250552/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
      with:
        node-version: '20.x'
        corepack: true

    - name: Set scripts execute permissions
      run: |
        chmod +x ./scripts/add-osx-cert.sh
        chmod +x ./scripts/shim.sh
        # 检查权限是否设置成功
        ls -la ./scripts/add-osx-cert.sh
        ls -la ./scripts/shim.sh

    - name: Install dependencies
      run: |
        yarn install

    - name: Run electron-rebuild
      run: |
        npx electron-rebuild
        
    - uses: apple-actions/import-codesign-certs@v1
      name: 安装APP证书
      with:
        p12-file-base64: ${{ secrets.APP_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
    
    - name: Generate keychain profile for notarization
      run: |
        xcrun notarytool store-credentials 'comfyui' \
          --apple-id "${{ secrets.USER_NAME }}" \
          --team-id "${{ secrets.TEAM_ID }}" \
          --password "${{ secrets.ACCOUNT_PASSWORD }}"

    - name: Create entitlements file
      run: |
        cat > Release.entitlements << 'EOL'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>com.apple.security.cs.allow-jit</key>
            <true/>
            <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
            <true/>
            <key>com.apple.security.cs.disable-library-validation</key>
            <true/>
            <key>com.apple.security.cs.disable-executable-page-protection</key>
            <true/>
            <key>com.apple.security.automation.apple-events</key>
            <true/>
            <key>com.apple.security.cs.allow-dyld-environment-variables</key>
            <true/>
        </dict>
        </plist>
        EOL
        cat Release.entitlements

    - name: Build project
      env:
        CSC_LINK: ${{ secrets.APP_BASE64 }}
        CSC_KEY_PASSWORD: ${{ secrets.P12_PASSWORD }}
        APPLE_ID: ${{ secrets.USER_NAME }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.TEAM_ID }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo "Building project..."
        # 确保使用正确的 electron-builder 配置
        # 添加以下内容到 package.json 的 build 配置或传递参数
        # "hardenedRuntime": true,
        # "gatekeeperAssess": false,
        # "entitlements": "Release.entitlements",
        # "entitlementsInherit": "Release.entitlements"
        yarn make
        
        # 找到构建的 app 文件
        APP_PATH=$(find ./dist/mac-arm64 -name "*.app" -type d | head -n 1)
        
        if [ -z "$APP_PATH" ]; then
          echo "App file not found"
          exit 1
        fi
        
        echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
        echo "APP_NAME=$(basename "$APP_PATH")" >> $GITHUB_ENV
        echo "App found: $APP_PATH"

    - name: Sign app and binaries with hardened runtime
      run: |
        # 首先需要签名所有内部的 dylib 和二进制文件
        echo "Finding and signing all binaries and libraries..."
        
        # 签名所有的 .dylib 文件
        find "${{ env.APP_PATH }}" -name "*.dylib" | while read -r file; do
          echo "Signing dylib: $file"
          codesign -f -o runtime --timestamp -s "${{ secrets.IDENTITY_NAME }}" "$file"
        done
        
        # 签名所有的 .node 文件
        find "${{ env.APP_PATH }}" -name "*.node" | while read -r file; do
          echo "Signing node: $file"
          codesign -f -o runtime --timestamp -s "${{ secrets.IDENTITY_NAME }}" "$file"
        done
        
        # 签名所有可执行文件
        find "${{ env.APP_PATH }}" -type f -perm +111 ! -path "*/.*" | while read -r file; do
          file_type=$(file -b "$file")
          if [[ $file_type == *"executable"* ]]; then
            echo "Signing executable: $file"
            codesign -f -o runtime --timestamp --entitlements ./Release.entitlements -s "${{ secrets.IDENTITY_NAME }}" "$file"
          fi
        done
        
        # 特别处理 Electron Helper 应用
        find "${{ env.APP_PATH }}" -path "*/Contents/Frameworks/Electron*Helper*.app" -type d | while read -r helper; do
          echo "Signing Electron Helper app: $helper"
          codesign -f -o runtime --timestamp --entitlements ./Release.entitlements -s "${{ secrets.IDENTITY_NAME }}" "$helper"
        done
        
        # 特别处理 framework
        find "${{ env.APP_PATH }}" -path "*/Contents/Frameworks/*.framework" -type d | while read -r framework; do
          echo "Signing framework: $framework"
          codesign -f -o runtime --timestamp -s "${{ secrets.IDENTITY_NAME }}" "$framework"
        done
        
        # 最后签名主应用
        echo "Signing the main .app bundle..."
        codesign -f -o runtime --deep --timestamp --entitlements ./Release.entitlements -s "${{ secrets.IDENTITY_NAME }}" "${{ env.APP_PATH }}"
        
        # 验证签名
        echo "Verifying app signature..."
        codesign -vvv --deep "${{ env.APP_PATH }}"
        
    - name: Create DMG from signed app
      run: |
        # 创建DMG文件名
        DMG_NAME="ComfyUI_Desktop_${TAG}.dmg"
        DMG_PATH="./dist/${DMG_NAME}"
        echo "DMG_PATH=$DMG_PATH" >> $GITHUB_ENV
        echo "DMG_NAME=$DMG_NAME" >> $GITHUB_ENV
        
        # 创建DMG
        echo "Creating DMG from signed app..."
        mkdir -p ./dist
        
        # 使用hdiutil创建DMG
        hdiutil create -volname "ComfyUI Desktop" -srcfolder "${{ env.APP_PATH }}" -ov -format UDZO "$DMG_PATH"
        
        if [ ! -f "$DMG_PATH" ]; then
          echo "DMG creation failed"
          exit 1
        fi
        
        echo "DMG created: $DMG_PATH"
        
        # 签名DMG文件
        echo "Signing DMG file..."
        codesign -f -o runtime --timestamp -s "${{ secrets.IDENTITY_NAME }}" "$DMG_PATH"

    - name: Notarize DMG
      run: |
        # 提交到公证服务
        echo "Submitting to Apple notarization service..."
        xcrun notarytool submit "${{ env.DMG_PATH }}" --keychain-profile "comfyui" --wait
        
        # 注入公证信息
        echo "Stapling notarization ticket to DMG..."
        xcrun stapler staple "${{ env.DMG_PATH }}"
        
        # 验证公证
        echo "Verifying notarization..."
        xcrun stapler validate "${{ env.DMG_PATH }}"
        spctl --assess -vv --type open "${{ env.DMG_PATH }}"

    # 检查 DMG 文件是否存在
    - name: Check final DMG file
      run: |
        if [ ! -f "${{ env.DMG_PATH }}" ]; then
          echo "Final DMG file not found"
          exit 1
        fi
        
        # 显示文件信息
        ls -la "${{ env.DMG_PATH }}"

    # 发布 DMG 到 Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ env.DMG_PATH }}"
        name: "ComfyUI Desktop ${{ env.TAG }}"
        body: "ComfyUI Desktop for macOS version ${{ env.TAG }}"
        draft: false
        prerelease: true  # 标记为预发布
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Send success notification to WeChat
      if: success()
      run: |
        WEBHOOK="${{ secrets.WECHAT_HOOK }}"
        curl -X POST "$WEBHOOK" \
        -H 'Content-Type: application/json' \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "构建成功: ComfyUI Desktop ${{ env.TAG }} 已发布。下载地址: https://github.com/${{ github.repository }}/releases/tag/${{ env.TAG }}/${{ env.DMG_NAME }}"
              }
            }'

    - name: Send failure notification to WeChat
      if: failure()
      run: |
        WEBHOOK="${{ secrets.WECHAT_HOOK }}"
        curl -X POST "$WEBHOOK" \
        -H 'Content-Type: application/json' \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "构建失败: ComfyUI Desktop ${{ env.TAG }} 构建过程中出现错误。"
              }
            }'